title: xTools4 user documentation
email: gustavo@hipertipo.com
description: xTools4 user documentation
baseurl: ''
url: https://gferreira.github.io/xTools4

collections:
  reference:
    output: true
    permalink: /:path/
  explanations:
    output: true
    permalink: /:path/
  howtos:
    output: true
    permalink: /:path/
  tutorials:
    output: true
    permalink: /:path/

markdown: kramdown

version: 0.2.9

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-tidy

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
